"use strict";
exports.__esModule = true;
var Cd_1 = require("./Cd");
var Dvd_1 = require("./Dvd");
var Bluray_1 = require("./Bluray");
var VentaDisco_1 = require("./VentaDisco");
var Cliente_1 = require("./Cliente");
var Tienda_1 = require("./Tienda");
var cd1 = new Cd_1.Cd('Los vengadores', 5, 50);
var cd2 = new Cd_1.Cd('La propuesta', 6, 40);
var dvd1 = new Dvd_1.Dvd('La bella durmiente', 7, 30);
var dvd2 = new Dvd_1.Dvd('La cenicienta', 8, 20);
var bluray1 = new Bluray_1.Bluray('Nacido para matar', 15, 10, true);
var bluray2 = new Bluray_1.Bluray('La huerfana', 20, 10, false);
var cliente1 = new Cliente_1.Cliente('Juancito', 'Perez', 21, 'frecuente');
var cliente2 = new Cliente_1.Cliente('Gladys', 'Zarsuri', 22, 'frecuente');
var cliente3 = new Cliente_1.Cliente('Luis', 'Ruiz', 12, 'poco frecuente');
var venta1 = new VentaDisco_1.VentaDisco(cd1, cliente1, '21-03-2019');
var venta2 = new VentaDisco_1.VentaDisco(dvd1, cliente2, '03-05-2019');
var venta3 = new VentaDisco_1.VentaDisco(bluray1, cliente3, '12-11-2019');
var venta4 = new VentaDisco_1.VentaDisco(cd1, cliente1, '21-03-2019');
var tienda = new Tienda_1.Tienda('El pato Lucas');
tienda.registrarPeliculas(cd1);
tienda.registrarPeliculas(cd2);
tienda.registrarPeliculas(dvd1);
tienda.registrarPeliculas(dvd2);
tienda.registrarPeliculas(bluray1);
tienda.registrarPeliculas(bluray2);
tienda.vender(venta2, 2);
tienda.vender(venta1, 2);
tienda.vender(venta3, 2);
tienda.vender(venta4, 2);
console.log('venta cds: ' + tienda.ventaCd());
console.log('venta dvds: ' + tienda.ventaDvd());
console.log('venta Bluray: ' + tienda.ventaBluray());
console.log('venta total:  ' + tienda.ventaTotal());
console.log('peliculas disponible antes de vender:');
console.log(tienda.peliculasDiponibles());
console.log('peliculas vendidas:');
console.log(tienda.peliculasVendidas());
console.log('peliculas disponible despues de vender:');
console.log(tienda.peliculasDiponibles());
